export const queryKeys = {
  timingTemplatesArchived: (producerId: string) =>
    ["timing-templates-archived", producerId] as const,
  seasonsArchived: ["seasons-archived"],
  me: ["me"],
  memberships: ["memberships"],
  quota: ["quota"],
  farms: ["farms"],
  farm: (id: string) => ["farm", id],
  farmPlots: (farmId: string) => ["farm-plots", farmId],
  farmSeasons: (farmId: string) => ["farm-seasons", farmId],
  farmAccess: (farmId: string) => ["farm-access", farmId],
  farmCycles: (farmId: string) => ["farm-cycles", farmId] as const,
  producerCycles: (producerId: string) =>
    ["producer-cycles", producerId] as const,
  cycle: (id: string) => ["cycle", id] as const,
  cycleAvailablePlots: (id: string) => ["cycle-available-plots", id] as const,
  cycleCostPlan: (id: string) => ["cycle-cost-plan", id] as const,
  cyclePurchaseList: (id: string) => ["cycle-purchase-list", id] as const,
  producers: ["producers"],
  producer: (id: string) => ["producer", id],
  producerFarms: (producerId: string) => ["producer-farms", producerId],
  producerStock: (producerId: string) => ["producer-stock", producerId],
  localCatalog: ["local-catalog"],
  inactiveLocalCatalog: ["inactiveLocalCatalog"],
  allLocalProducts: ["allLocalProducts"],
  allInactiveLocalProducts: ["allInactiveLocalProducts"],
  globalCatalog: ["global-catalog"],
  platformCatalog: ["platform-catalog"],
  adminPlatformActive: ["admin-platform-active"],
  adminDeactivatedCatalog: ["admin-deactivated-catalog"],
  seasons: ["seasons"],
  season: (id: string) => ["season", id],
  seasonTimeline: (seasonId: string) => ["season-timeline", seasonId],
  seasonShoppingList: (seasonId: string) => ["season-shopping-list", seasonId],
  notifications: ["notifications"],
  timingTemplates: (producerId: string) => ["timing-templates", producerId] as const,
  timingTemplate: (id: string) => ["timing-template", id],
  mixTemplates: ["mix-templates"],
  mixTemplate: (id: string) => ["mix-template", id],
  plans: ["plans"],
  adminAgronomists: (status: "active" | "inactive") => ["admin-agronomists", status] as const,
  adminAgronomistDetail: (id: string) => ["admin-agronomist-detail", id] as const,
  adminProducers: ["admin-producers"],
  adminTeamMembers: (filters?: { agronomist_id?: string; temporary?: boolean }) =>
    ["admin-team-members", filters?.agronomist_id ?? "all", filters?.temporary ? "temp" : "all"] as const,
  organizations: ["organizations"] as const,
  organizationMembers: (id: string) => ["organization-members", id] as const,
  farmTeam: (producerId: string) => ["farm-team", producerId] as const,
  farmTeamAll: ["farm-team-all"] as const,
  invitationToken: (token: string) => ["invitation-token", token],
  invitations: (kind?: string) => ["invitations", kind ?? "all"] as const,
  comparativeReport: ["comparative-report"],
  producerPurchaseLists: (producerId: string) => ["producer-purchase-lists", producerId] as const,
  purchaseListsCoverage: (scope: string) => ["purchase-lists-coverage", scope] as const,
  farmPurchaseLists: (farmId: string) => ["farm-purchase-lists", farmId] as const,
  purchaseListTemplates: () => ["purchase-list-templates"] as const,
  seasonCostPlan: (seasonId: string) => ["season-cost-plan", seasonId] as const,
  purchaseListQuotes: (listId: string) => ["purchase-list-quotes", listId] as const,
  purchaseListQuoteTrash: (listId: string) => ["purchase-list-quote-trash", listId] as const,
  purchaseListProgress: (listId: string) => ["purchase-list-progress", listId] as const,
  stockOrigins: (producerId: string, localProductId: string) =>
    ["stock-origins", producerId, localProductId] as const,
  stockHistory: (producerId: string, q?: string) =>
    ["stock-history", producerId, q ?? ""] as const,
  quoteByToken: (token: string) => ["quote-by-token", token] as const,
  quoteResponse: (responseToken: string) => ["quote-response", responseToken] as const,
  agronomistAgenda: (producerId?: string) =>
    ["agronomist-agenda", producerId ?? "all"] as const,
  plotHistory: (seasonId: string) => ["plot-history", seasonId] as const,
};
