export const queryKeys = {
  timingTemplatesArchived: (producerId: string) =>
    ["timing-templates-archived", producerId] as const,
  mixTemplatesArchived: ["mix-templates-archived"],
  seasonsArchived: ["seasons-archived"],
  me: ["me"],
  quota: ["quota"],
  farms: ["farms"],
  farm: (id: string) => ["farm", id],
  farmPlots: (farmId: string) => ["farm-plots", farmId],
  farmSeasons: (farmId: string) => ["farm-seasons", farmId],
  farmAccess: (farmId: string) => ["farm-access", farmId],
  producers: ["producers"],
  producer: (id: string) => ["producer", id],
  producerFarms: (producerId: string) => ["producer-farms", producerId],
  producerStock: (producerId: string) => ["producer-stock", producerId],
  localCatalog: ["local-catalog"],
  inactiveLocalCatalog: ["inactiveLocalCatalog"],
  allLocalProducts: ["allLocalProducts"],
  allInactiveLocalProducts: ["allInactiveLocalProducts"],
  globalCatalog: ["global-catalog"],
  platformCatalog: ["platform-catalog"],
  adminPlatformActive: ["admin-platform-active"],
  adminDeactivatedCatalog: ["admin-deactivated-catalog"],
  seasons: ["seasons"],
  season: (id: string) => ["season", id],
  seasonTimeline: (seasonId: string) => ["season-timeline", seasonId],
  seasonShoppingList: (seasonId: string) => ["season-shopping-list", seasonId],
  notifications: ["notifications"],
  timingTemplates: (producerId: string) => ["timing-templates", producerId] as const,
  timingTemplate: (id: string) => ["timing-template", id],
  mixTemplates: ["mix-templates"],
  mixTemplate: (id: string) => ["mix-template", id],
  plans: ["plans"],
  adminAgronomists: (status: "active" | "inactive") => ["admin-agronomists", status] as const,
  adminAgronomistDetail: (id: string) => ["admin-agronomist-detail", id] as const,
  adminProducers: ["admin-producers"],
  invitationToken: (token: string) => ["invitation-token", token],
  comparativeReport: ["comparative-report"],
  producerPurchaseLists: (producerId: string) => ["producer-purchase-lists", producerId] as const,
  farmPurchaseLists: (farmId: string) => ["farm-purchase-lists", farmId] as const,
  seasonCostPlan: (seasonId: string) => ["season-cost-plan", seasonId] as const,
  purchaseListQuotes: (listId: string) => ["purchase-list-quotes", listId] as const,
  quoteByToken: (token: string) => ["quote-by-token", token] as const,
  quoteResponse: (responseToken: string) => ["quote-response", responseToken] as const,
  agronomistAgenda: (producerId?: string) =>
    ["agronomist-agenda", producerId ?? "all"] as const,
};
